### ISSUE TITLE
Allow users to input HTML code.

### ISSUE THREAD

**Issue by pexeixv** [Devzstudio/tailwind_to_css#12]
Allow users to input HTML code like

```html
 <h1 class="flex-grow font-bold flex items-center text-gray-300 md:mr-2">An example</h1>
```
and get presented with the CSS like
```css
.flex{display: flex;}
.text-gray-300{color: #D1D5DB;}
.font-bold{font-weight: 700;}
.flex-grow{flex-grow: 1;}
.items-center{align-items: center;}
@media (min-width: 768px) { 
  md:\mr-2{margin-right: 0.5rem;}
 }
```
