### ISSUE TITLE
Gradients

### ISSUE THREAD

**Issue by new-user-name** [Devzstudio/tailwind_to_css#31]
Hi,
`bg-gradient-to-r from-purple-500 to-pink-500`
gives 
```
background-image: background-image: linear-gradient(to right, var(--tw-gradient-stops)); 
background-color: #8B5CF6; 
background-color: #EC4899;
```

Shouldn't it be
--tw-gradient-from: #8B5CF6;
  --tw-gradient-to: #EC4899;
  --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to);
  background-image: linear-gradient(to right, var(--tw-gradient-stops));

or even
`background-image: linear-gradient(to right, #8B5CF6, #EC4899);`

**Comment by ADTC** [comment]
I believe [the output should be](https://tailwind-to-css-three.vercel.app/):
```css
.generated {
  background-image: linear-gradient(to right, var(--tw-gradient-stops));
  --tw-gradient-from: #a855f7 var(--tw-gradient-from-position);
  --tw-gradient-to: rgb(168 85 247 / 0) var(--tw-gradient-to-position);
  --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to);
  --tw-gradient-to: #ec4899 var(--tw-gradient-to-position)
}
```
